version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: mcp-server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./mcp-server/.env
    restart: unless-stopped
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: mcp-client/Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - server

volumes:
  postgres_data: